# Source: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # Test with the latest LTS version of Node (https://nodejs.org/)
          node-version: '14'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
